### ISSUE TITLE
App crashes after selecting image/taking photo

### ISSUE THREAD

**Issue by oldschoolBavarianReferenceSystem** [diedricm/MapEver#1]
After selecting a photo from the gallery or after taking a photo with the camera and clicking the OK-Button, the App crashes without any note.

If I press the Cancel-Button after Taking a Photo, I get back to the main App window.

MapEver is from F-Droid, Version 1.0
Motorola Razr I, Android 4.1.2

**Comment by oldschoolBavarianReferenceSystem** [comment]
Could be a problem with the F-Droid-Version, as this is compiled for ARM, but the Razr I has an intel processor.

Here is the build-script:

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/de.hu_berlin.informatik.spws2014.mapever.txt

Line 28:

```
&& sh ./scripts/cmake_android_arm.sh \
```

**Comment by diedricm** [comment]
Thanks for the report. Yes currently MapEver only includes the armeabi-v7a librarys of OpenCV. Adding all OpenCV librarys would make the apk much bigger.

I will try to modify the buildscript this weekend to also add releases for the other architectures.

**Comment by oldschoolBavarianReferenceSystem** [comment]
Thanks for your help.

I looked a bit further into this. The Razr performs an on-the-fly translation of ARM-code into x86 code. 

I found out that `android.os.Build.CPU_ABI API = “x86”` and `android.os.Build.CPU_ABI2=“armeabi-v7a”`. The device translates with libhoudini.

There seams to be a problem with a specific code or translation:

04-23 22:30:36.289 10610 10610 D EntzerrungsView/getSampledBitmap: Decoding stream with sample size 10...
04-23 22:30:36.299   386   398 D hwcomposer: isOverlayLayer: got an overlay layer
04-23 22:30:36.299   386   398 D hwcomposer: isSpriteLayer: got a sprite layer
04-23 22:30:36.299   386   398 D hwcomposer: void IntelHWComposerLayerList::clearWithOpenGL() const: clear fb here, size 540 x 960
04-23 22:30:36.319   386   398 D hwcomposer: isOverlayLayer: got an overlay layer
04-23 22:30:36.319   386   398 D hwcomposer: isSpriteLayer: got a sprite layer
04-23 22:30:36.319   386   398 D hwcomposer: void IntelHWComposerLayerList::clearWithOpenGL() const: clear fb here, size 540 x 960
04-23 22:30:36.339   386   398 D hwcomposer: isOverlayLayer: got an overlay layer
04-23 22:30:36.339   386   398 D hwcomposer: isSpriteLayer: got a sprite layer
04-23 22:30:36.339   386   398 D hwcomposer: void IntelHWComposerLayerList::clearWithOpenGL() const: clear fb here, size 540 x 960
04-23 22:30:37.119 10610 10610 D houdini : [10610] Unsupported feature (ID:0x010007c2).
04-23 22:30:37.119 10610 10610 F libc    : Fatal signal 11 (SIGSEGV) at 0xdead0000 (code=1), thread 10610 (pws2014.mapever)
04-23 22:30:37.179   140   140 I DEBUG   : **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
04-23 22:30:37.179   140   140 I DEBUG   : Build fingerprint: 'motorola/XT890_rtcoreeu/
04-23 22:30:37.179   140   140 I DEBUG   : pid: 10610, tid: 10610, name: pws2014.mapever  >>> de.hu_berlin.informatik.spws2014.mapever <<<
04-23 22:30:37.179   140   140 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr dead0000
04-23 22:30:37.939   140   140 I DEBUG   :     eax 00000000  ebx bf814ed4  ecx 53ceaf7c  edx 00000000
04-23 22:30:37.939   140   140 I DEBUG   :     esi 0000023d  edi 392d133a
04-23 22:30:37.939   140   140 I DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
04-23 22:30:37.939   140   140 I DEBUG   :     eip 53af8d23  ebp bf814eec  esp bf814ec4  flags 00210246
04-23 22:30:37.939   140   140 I DEBUG   : 
04-23 22:30:37.939   140   140 I DEBUG   : memory map around fault addr dead0000:
04-23 22:30:37.939   140   140 I DEBUG   :     bf7f5000-bf816000 [stack]
04-23 22:30:37.939   140   140 I DEBUG   :     (no map for address)
04-23 22:30:37.939   140   140 I DEBUG   :     (no map above)
04-23 22:30:38.029   386   418 I BootReceiver: Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
04-23 22:30:38.039   386   882 I WindowState: WIN DEATH: Window{2131efc0 de.hu_berlin.informatik.spws2014.mapever/de.hu_berlin.informatik.spws2014.mapever.Start paused=false}
04-23 22:30:38.039   386   397 I ActivityManager: Process de.hu_berlin.informatik.spws2014.mapever (pid 10610) has died.
04-23 22:30:38.039   386   397 W ActivityManager: Force removing ActivityRecord{21649468 de.hu_berlin.informatik.spws2014.mapever/.entzerrung.Entzerren}: app died, no saved state

....
I think the ARM-translation/simulation is also the reason why the stacktrace doesn't have much more information.

So, a specific x86 .apk would be cool, I haven't set up a NDK yet.

**Comment by rdoeffinger** [comment]
Another option would be to have a build without OpenCV support at all.
At least I hardly ever have any use for the deskewing anyway, and I ended up hacking in support for missing OpenCV to make it easier to quickly compile and test things.
I'll send a pull request for that change later (it's just a matter of catching the load error).

**Comment by diedricm** [comment]
First sorry I kinda neglected this.

A problem with removing OpenCV is that it is not only used for deskewing but also for triangulating in src/de/hu_berlin/informatik/spws2014/imagePositionLocator/ImagePositionLocator.java in the function public "void newMarkerAdded(List<Marker> markers)". It would be possible to write a new triangulation algorithm for MapEver, or to take a existing Java Implementation like https://code.google.com/p/poly2tri/ , but I will probably not do it right now.

I am also a little discouraged to add x86 and potentially also armeabi to f-droid, as the tarball size for each version is around 80MB and to date the app was only downloaded <300 times.

I will try to add the binary for x86 to the github "releases" tab this evening using a private certificate. I cannot test this on any real device however, as I do not own any x86 androids.

**Comment by rdoeffinger** [comment]
Ah, I didn't get far enough on the emulator to test the locator code.
Which reminds me: any chance of adding some build system to git? My attempts to import into AndroidStudio for example resulted it in making a copy and messing around with the layout so I am having trouble even creating a diff, though at least it does work... I thoroughly hate Android development tools, never used anything as crappy (for my usage patterns at least) in the last 10 years on any OS.
But my plan was to try to replace that algorithm anyway, it seems to my that trying to put all points into triangles might have some strange effects.
I would like to try a weighted linear least-squares solver, which should allow weighing individual markers, and both based on distance to current position and potentially by accuracy of the gps position when it was added.
But as for it will likely be a bit until I actually manage to do it, but just some heads up on my plans (and a chance to stop me if you tried something like that and it didn't work).
And sorry for dragging this somewhat off-topic.

**Comment by diedricm** [comment]
Wow. I'm really happy that someone even looks at the code :D
As for the build system: Currently this is not compatible with the android-studio/graddle build tools, as we mostly used eclipse-adt/ant internally. You can import it into Eclipse as an Existing Android Project and place the OpenCV libs under /libs. This should work. Maybe @LockeFromTheBlock can give you some tips as to how to integrate this into android-studio.

About replacing the algorithm: Someone in the team tried to use linear regression for this, but as the triangle solution worked faster it got dropped. For changing the algorithm you would only need to change ImagePositionLocator.java and potentially remove ProjectionTriangles.java. If you want to work with the accurency values the LocationListener provides, then you would also want to add such a member to GpsPoint.java.

It would be a lot nicer if the LocationDataManager would support plugable algorithm backends at runtime ... maybe I'll do that sometime. Another cool thing would be if imagePositionLocator would be its own library. If you'd want to I could also upload a java application i wrote for testing the algorithm on desktop through a google earth like interface.

Maybe further discussion on this should happen in a separate issue, otherwise we might annoy OP.

**Comment by diedricm** [comment]
I uploaded the x68 apk in the releases tab. This should help for the moment.

**Comment by oldschoolBavarianReferenceSystem** [comment]
Thank you, it works.
