### ISSUE TITLE
LargeImageView crashes

### ISSUE THREAD

**Issue by diedricm** [diedricm/MapEver#6]
@rdoeffinger said:

> I'll also have to check if I can do something about crashes when I use a full-resolution camera image and zoom in, is that a known thing? (just in case you know)

Let us talk about this here. I assume it crashes with an OOM exception? How much RAM does your testing device have? Both the deskewing and the navigation view tile the image and use a cache to store the tiles. We once had a problem that some native android library crashed when we tried to decode multiple tiles at once into the cache, but currently it should be doing them one after another. This happened mostly on older devices. It also might be that the cache size is too big for your device, but I think it's chosen relative to the amount of free memory.

**Comment by rdoeffinger** [comment]
Yes, it is indeed OOM.
The device is a Galaxy S2, so 1 GB RAM. Which to me seems plenty for displaying a 8 MPixel image...

**Comment by diedricm** [comment]
That should be more than enough ... could you provide a little more information like stacktrace, log and so on?
@Steltie will you look at this?

**Comment by rdoeffinger** [comment]
Having a bit of trouble transferring logs.
But why does the CachedImage.java store tiles per sample size??
That means that the maximum about of memory stored bloats from a mere 32 MB to a full 1GB(!!!) if you end up storing all tiles for all scales!
Also generateTileBitmap generally seems really fishy to me.
Doxygen: @return Bitmap des Tiles (maximal TILESIZE*TILESIZE Pixel groß)
Code: int right = Math.min(getWidth(), left + sampleSize * TILESIZE);
Which to me looks it will be up to 32*TILESIZE large.
If I read that right, that "memory saving" cache actually manages to bloat a max image size of 32 MB up by a factor 32*32*32 for an amazing memory usage of 1TB?? (well, if it wouldn't throw things out before)...
(trying to convince github to not interpret as markdown...)

**Comment by rdoeffinger** [comment]
Ok, now after some more reading I am convinced I thoroughly misunderstand some things here. Not sure that counts as progress though.

**Comment by diedricm** [comment]
As I said I also now little about that code. It cant be completely wrong however, as it already worked on several android devices with 512MB ram and fairly old android versions. It would be very helpful if you would post stacktraces and logs.

**Comment by rdoeffinger** [comment]
This actually lead to the thumbnail fix. I actually can't reproduce it any more after that.
I suspect that the non-thumbnail thumbnails ate all the memory thought for this cache, and thus the crashes.

**Comment by diedricm** [comment]
So it crashed on the start screen for you? I thought it was navigation or deskewing.

**Comment by rdoeffinger** [comment]
It definitely also crashed when returning to the start screen.
But no it crashed during navigation.
My theory is that only the high memory usage of the start screen together with the tile cache pushed it over the limit.
Thinking about it, that would mean that the "thumbnails" were not deallocated after switching away from the start screen. Not sure that is the case/intended, but that is my best theory.
Either ways I can't reproduce crashes anymore (not even using the same image and emulator reduced for 512 MB - however for that configuration I get some flickering due to loading one tile throwing out another that is actually visible).

**Comment by rdoeffinger** [comment]
As you merged the thumbnail fix you can close this from my side, even though there are potential improvements in the area they don't qualify as a bug to me for now.

**Comment by diedricm** [comment]
The start screen is definitely something we should not waste time on. There is very much hacked and there’s no caching at all. It would make much more sense to just write that screen anew imho. However nice that it should at least allow many more maps before oom happens.
